name: Simple AWS Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'JNv3/**'
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

env:
  AWS_REGION: us-east-1
  PROJECT_NAME: jobquest-navigator-v3

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.6.0'
        terraform_wrapper: false
    
    - name: Terraform Init
      run: |
        cd JNv3/infrastructure/simple-terraform
        terraform init -backend=false
    
    - name: Terraform Plan (Simple Deployment)
      env:
        TF_VAR_project_name: ${{ env.PROJECT_NAME }}
        TF_VAR_aws_region: ${{ env.AWS_REGION }}
      run: |
        cd JNv3/infrastructure/simple-terraform
        terraform plan -no-color
    
    - name: Terraform Apply (Simple Deployment)
      env:
        TF_VAR_project_name: ${{ env.PROJECT_NAME }}
        TF_VAR_aws_region: ${{ env.AWS_REGION }}
      run: |
        cd JNv3/infrastructure/simple-terraform
        terraform apply -auto-approve -no-color
    
    - name: Get deployment outputs
      id: terraform-outputs
      run: |
        cd JNv3/infrastructure/simple-terraform
        echo "website_url=$(terraform output -raw website_url 2>/dev/null || echo 'Not available')" >> $GITHUB_OUTPUT
        echo "bucket_name=$(terraform output -raw s3_bucket_name 2>/dev/null || echo 'Not available')" >> $GITHUB_OUTPUT
    
    - name: Deployment Summary
      run: |
        echo "## 🚀 CAA900 Deployment Complete" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Project:** JobQuest Navigator v3" >> $GITHUB_STEP_SUMMARY
        echo "**Student:** Kevin Wang" >> $GITHUB_STEP_SUMMARY
        echo "**Course:** CAA900 Software Development Capstone" >> $GITHUB_STEP_SUMMARY
        echo "**Environment:** AWS Production" >> $GITHUB_STEP_SUMMARY
        echo "**Website URL:** ${{ steps.terraform-outputs.outputs.website_url }}" >> $GITHUB_STEP_SUMMARY
        echo "**S3 Bucket:** ${{ steps.terraform-outputs.outputs.bucket_name }}" >> $GITHUB_STEP_SUMMARY
        echo "**Deployed at:** $(date)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ✅ Course Requirements Met:" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Live HTTPS deployment on AWS" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Infrastructure as Code with Terraform" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Automated CI/CD pipeline" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Professional project structure" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Modern technology stack" >> $GITHUB_STEP_SUMMARY